// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Infrastructure.EFModel
{
    public partial class Clanarina
    {
        public Clanarina()
        {
            Racun = new HashSet<Racun>();
        }

        public int IdClanarina { get; set; }
        public string NazivClanarina { get; set; }
        public int OdGodine { get; set; }
        public int DoGodine { get; set; }
        public decimal CijenaClanarina { get; set; }

        public virtual ICollection<Racun> Racun { get; set; }
    }
}