// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Infrastructure.EFModel
{
    public partial class Mjesto
    {
        public Mjesto()
        {
            Osoba = new HashSet<Osoba>();
        }

        public int IdMjesto { get; set; }
        public string Pbr { get; set; }
        public string NazivMjesto { get; set; }

        public virtual ICollection<Osoba> Osoba { get; set; }
    }
}