// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Infrastructure.EFModel
{
    public partial class Osoba
    {
        public Osoba()
        {
            Racun = new HashSet<Racun>();
            Rezervacija = new HashSet<Rezervacija>();
        }

        public int IdOsoba { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Adresa { get; set; }
        public int IdMjesto { get; set; }
        public int IdUloga { get; set; }
        public int Status { get; set; }
        public string Oib { get; set; }
        public DateTime DatumRodenja { get; set; }
        public DateTime DatumPrijave { get; set; }
        public string Email { get; set; }
        public string Username { get; set; }
        public string Lozinka { get; set; }
        public string Telefon { get; set; }

        public virtual Mjesto IdMjestoNavigation { get; set; }
        public virtual Uloga IdUlogaNavigation { get; set; }
        public virtual ICollection<Racun> Racun { get; set; }
        public virtual ICollection<Rezervacija> Rezervacija { get; set; }
    }
}