// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Infrastructure.EFModel
{
    public partial class Racun
    {
        public Racun()
        {
            Rezervacija = new HashSet<Rezervacija>();
        }

        public int IdRacun { get; set; }
        public DateTime DatumRacuna { get; set; }
        public bool? RacunPlacen { get; set; }
        public decimal Ukupno { get; set; }
        public int IdOsoba { get; set; }
        public int IdClanarina { get; set; }

        public virtual Clanarina IdClanarinaNavigation { get; set; }
        public virtual Osoba IdOsobaNavigation { get; set; }
        public virtual ICollection<Rezervacija> Rezervacija { get; set; }
    }
}