// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Infrastructure.EFModel
{
    public partial class RezerviranaUsluga
    {
        public int IdRezervacija { get; set; }
        public int IdUsluga { get; set; }
        public DateTime PocetakUsluge { get; set; }
        public DateTime ZavrsetakUsluge { get; set; }

        public virtual Rezervacija IdRezervacijaNavigation { get; set; }
        public virtual Usluga IdUslugaNavigation { get; set; }
    }
}