// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Infrastructure.EFModel
{
    public partial class Rezervacija
    {
        public Rezervacija()
        {
            RezerviranaUsluga = new HashSet<RezerviranaUsluga>();
        }

        public int IdRezervacija { get; set; }
        public DateTime DatumPocetka { get; set; }
        public DateTime DatumZavrsetka { get; set; }
        public decimal CijenaRezervacije { get; set; }
        public int? IdRacun { get; set; }
        public DateTime DatumKreiranja { get; set; }
        public int IdOsoba { get; set; }

        public virtual Osoba IdOsobaNavigation { get; set; }
        public virtual Racun IdRacunNavigation { get; set; }
        public virtual ICollection<RezerviranaUsluga> RezerviranaUsluga { get; set; }
    }
}