// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Infrastructure.EFModel
{
    public partial class Uloga
    {
        public Uloga()
        {
            Osoba = new HashSet<Osoba>();
        }

        public int IdUloga { get; set; }
        public string NazivUloga { get; set; }

        public virtual ICollection<Osoba> Osoba { get; set; }
    }
}