// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Infrastructure.EFModel
{
    public partial class Usluga
    {
        public Usluga()
        {
            RezerviranaUsluga = new HashSet<RezerviranaUsluga>();
        }

        public int IdUsluga { get; set; }
        public string NazivUsluga { get; set; }
        public decimal CijenaPoSatu { get; set; }
        public int Kapacitet { get; set; }

        public virtual ICollection<RezerviranaUsluga> RezerviranaUsluga { get; set; }
    }
}